class TabModel {
  String place;
  String type;
  String date;
  String classname;
  bool isAvailable;
  final String instructor;
  final String from;
  final String to;
  TabModel({
    required this.isAvailable,
    required this.place,
    required this.type,
    required this.date,
    required this.classname,
    required this.instructor,
    required this.from,
    required this.to,
  });
}

final List<TabModel> allItems = [
  TabModel(
    place: 'Lab A',
    date: '16',
    type: 'Lab',
    classname: "5A",
    isAvailable: true,
    instructor: 'Mr. Ahmed',
    from: '08:00',
    to: '09:30',
  ),
  TabModel(
    place: 'P.E. Gym',
    date: '16',
    type: 'P.E.',
    classname: "5B",
    isAvailable: true,
    instructor: 'Coach Samir',
    from: '09:45',
    to: '10:30',
  ),
  TabModel(
    place: '4B',
    date: '16',
    type: 'Class',
    classname: "4A",
    isAvailable: false,
    instructor: 'Ms. Nadia',
    from: '10:45',
    to: '11:30',
  ),
  TabModel(
    place: 'Lab D',
    date: '17',
    type: 'Lab',
    classname: "4B",
    isAvailable: false,
    instructor: 'Mr. Karim',
    from: '08:00',
    to: '09:00',
  ),
  TabModel(
    place: 'P.E. Gym',
    date: '17',
    type: 'P.E.',
    classname: "2B",
    isAvailable: true,
    instructor: 'Coach Hossam',
    from: '09:15',
    to: '10:00',
  ),
  TabModel(
    place: '3B',
    date: '17',
    type: 'Class',
    classname: "5A",
    isAvailable: true,
    instructor: 'Ms. Dina',
    from: '10:15',
    to: '11:00',
  ),
  TabModel(
    place: 'P.E.',
    date: '18',
    type: 'P.E.',
    classname: "4A",
    isAvailable: true,
    instructor: 'Coach Samir',
    from: '08:30',
    to: '09:15',
  ),
  TabModel(
    place: 'Lab C',
    date: '18',
    type: 'Lab',
    classname: "4B",
    isAvailable: false,
    instructor: 'Mr. Tarek',
    from: '09:30',
    to: '10:30',
  ),
  TabModel(
    place: 'Lab A',
    date: '18',
    type: 'Lab',
    classname: "5A",
    isAvailable: false,
    instructor: 'Mr. Ahmed',
    from: '10:45',
    to: '11:30',
  ),
  TabModel(
    place: 'Lab D',
    date: '19',
    type: 'Lab',
    classname: "4A",
    isAvailable: true,
    instructor: 'Ms. Mona',
    from: '08:00',
    to: '09:00',
  ),
  TabModel(
    place: 'P.E. Gym',
    date: '19',
    type: 'P.E.',
    classname: "4B",
    isAvailable: true,
    instructor: 'Coach Hossam',
    from: '09:15',
    to: '10:00',
  ),
  TabModel(
    place: 'Lab D',
    date: '19',
    type: 'Lab',
    classname: "5B",
    isAvailable: false,
    instructor: 'Mr. Karim',
    from: '10:15',
    to: '11:00',
  ),
  TabModel(
    place: '5B',
    date: '20',
    type: 'Class',
    classname: "5B",
    isAvailable: true,
    instructor: 'Ms. Rania',
    from: '08:00',
    to: '08:45',
  ),
  TabModel(
    place: '5A',
    date: '20',
    type: 'Class',
    classname: "5A",
    isAvailable: false,
    instructor: 'Mr. Youssef',
    from: '09:00',
    to: '09:45',
  ),
  TabModel(
    place: '4B',
    date: '20',
    type: 'Class',
    classname: "2A",
    isAvailable: true,
    instructor: 'Ms. Nadine',
    from: '10:00',
    to: '10:45',
  ),
];
List<TabModel> filteredSessions = [];
