class TabModel {
  String place;
  String type;
  String date;
  String classname;
  bool isAvailable;
  final String instructor;
  final String from;
  final String to;
  TabModel({
    required this.isAvailable,
    required this.place,
    required this.type,
    required this.date,
    required this.classname,
    required this.instructor,
    required this.from,
    required this.to,
  });
}

final List<TabModel> allItems = [
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '16',
    classname: '4A',
    isAvailable: false,
    instructor: 'Mustafa',
    from: '08:00',
    to: '08:50',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '16',
    classname: '4B',
    isAvailable: false,
    instructor: 'Mohamed',
    from: '08:50',
    to: '09:40',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '16',
    classname: '5A',
    isAvailable: false,
    instructor: 'Amr',
    from: '09:40',
    to: '10:30',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '16',
    classname: '1A',
    isAvailable: false,
    instructor: 'Lamiaa',
    from: '11:00',
    to: '11:50',
  ),
  TabModel(
    place: '4A',
    type: 'Class',
    date: '16',
    classname: '4A',
    isAvailable: false,
    instructor: 'Hesham',
    from: '11:50',
    to: '12:40',
  ),

  // ------ free for 16 (labs) ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ------ free for 16 (classes & P.E.) ------
  TabModel(
    place: '4B',
    type: 'Class',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5A',
    type: 'Class',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5B',
    type: 'Class',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '16',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ==================== 17 ====================
  // ------ occupied ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '17',
    classname: '5A',
    isAvailable: false,
    instructor: 'Mazen',
    from: '08:00',
    to: '08:50',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '17',
    classname: '5B',
    isAvailable: false,
    instructor: 'Mustafa',
    from: '08:50',
    to: '09:40',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '17',
    classname: '4A',
    isAvailable: false,
    instructor: 'Mohamed',
    from: '09:40',
    to: '10:30',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '17',
    classname: '1B',
    isAvailable: false,
    instructor: 'Lamiaa',
    from: '11:00',
    to: '11:50',
  ),
  TabModel(
    place: '5B',
    type: 'Class',
    date: '17',
    classname: '5B',
    isAvailable: false,
    instructor: 'Wael',
    from: '11:50',
    to: '12:40',
  ),

  // ------ free for 17 (labs) ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ------ free for 17 (classes & P.E.) ------
  TabModel(
    place: '4A',
    type: 'Class',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '4B',
    type: 'Class',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5A',
    type: 'Class',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '17',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ==================== 18 ====================
  // ------ occupied ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '18',
    classname: '2A',
    isAvailable: false,
    instructor: 'Amr',
    from: '08:00',
    to: '08:50',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '18',
    classname: '2B',
    isAvailable: false,
    instructor: 'Mazen',
    from: '08:50',
    to: '09:40',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '18',
    classname: '3A',
    isAvailable: false,
    instructor: 'Mustafa',
    from: '09:40',
    to: '10:30',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '18',
    classname: '3B',
    isAvailable: false,
    instructor: 'Lamiaa',
    from: '11:00',
    to: '11:50',
  ),
  TabModel(
    place: '4B',
    type: 'Class',
    date: '18',
    classname: '4B',
    isAvailable: false,
    instructor: 'Khaled',
    from: '11:50',
    to: '12:40',
  ),

  // ------ free for 18 (labs) ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ------ free for 18 (classes & P.E.) ------
  TabModel(
    place: '4A',
    type: 'Class',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5A',
    type: 'Class',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5B',
    type: 'Class',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '18',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ==================== 19 ====================
  // ------ occupied ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '19',
    classname: '4A',
    isAvailable: false,
    instructor: 'Mohamed',
    from: '08:00',
    to: '08:50',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '19',
    classname: '4B',
    isAvailable: false,
    instructor: 'Amr',
    from: '08:50',
    to: '09:40',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '19',
    classname: '5A',
    isAvailable: false,
    instructor: 'Mazen',
    from: '09:40',
    to: '10:30',
  ),
  TabModel(
    place: '5A',
    type: 'Class',
    date: '19',
    classname: '5A',
    isAvailable: false,
    instructor: 'Haroun',
    from: '11:00',
    to: '11:50',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '19',
    classname: '2A',
    isAvailable: false,
    instructor: 'Lamiaa',
    from: '11:50',
    to: '12:40',
  ),

  // ------ free for 19 (labs) ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ------ free for 19 (classes & P.E.) ------
  TabModel(
    place: '4A',
    type: 'Class',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '4B',
    type: 'Class',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5B',
    type: 'Class',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '19',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ==================== 20 ====================
  // ------ occupied ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '20',
    classname: '1A',
    isAvailable: false,
    instructor: 'Mustafa',
    from: '08:00',
    to: '08:50',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '20',
    classname: '1B',
    isAvailable: false,
    instructor: 'Mohamed',
    from: '08:50',
    to: '09:40',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '20',
    classname: '2A',
    isAvailable: false,
    instructor: 'Amr',
    from: '09:40',
    to: '10:30',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '20',
    classname: '4A',
    isAvailable: false,
    instructor: 'Lamiaa',
    from: '11:00',
    to: '11:50',
  ),
  TabModel(
    place: '4B',
    type: 'Class',
    date: '20',
    classname: '4B',
    isAvailable: false,
    instructor: 'Sayed',
    from: '11:50',
    to: '12:40',
  ),

  // ------ free for 20 (labs) ------
  TabModel(
    place: 'Lab A',
    type: 'Lab',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab C',
    type: 'Lab',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'Lab D',
    type: 'Lab',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),

  // ------ free for 20 (classes & P.E.) ------
  TabModel(
    place: '4A',
    type: 'Class',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5A',
    type: 'Class',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: '5B',
    type: 'Class',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
  TabModel(
    place: 'P.E. Hall',
    type: 'P.E.',
    date: '20',
    classname: '',
    isAvailable: true,
    instructor: '',
    from: '',
    to: '',
  ),
];
